### ISSUE TITLE
What fonts are needed for your conkyrc file?

### ISSUE THREAD

**Issue by cmoro-deusto** [Martinsos/dotfiles#4]
Hi! Read your post showing your conky setup and looks awesome. I downloaded the conkyrc file, but icons don't show up. I guess it's because I'm missing some fonts.

Thanks a lot!!

**Comment by Martinsos** [comment]
Hi @cmoro-deusto, thanks for your kind words :)!
If you check the comments at the top of the file, it lists all dependencies, and one of them is `conky-colors` -> that package brings the fonts that are used for the icons.
For example, if you check the line for the CPU:
```
${goto 6}${voffset 4}${font conkycolors:size=16}d${font}${voffset -5}${goto 32}Frequency: ${alignr}${freq_g (1)} GHz
```
You will see the part `${font conkycolors:size=16}d` which actually creates that icon.
I am on archlinux, so I installed [conky-colors from AUR](https://aur.archlinux.org/packages/conky-colors-git/). I don't know on which distro are you, but I guess there should also be packages for other distros.

**Comment by cmoro-deusto** [comment]
Hi @Martinsos 

thanks a lot for your reply. I'm sorry! I was so, so sure I installed the dependencies that I didn't check them back... doh! Of course, after actually installing conky-colors (I'm also on Arch :D), everything works flawlessly.

Cheers!

**Comment by Martinsos** [comment]
Awesome, and if you make any awesome modifications let me know, maybe I could also update mine :)!

**Comment by cmoro-deusto** [comment]
Need to get some free time to play with it a bit, but I added GPU frequency (next to GPU name):

```
${goto 6}${voffset 5}${font conkycolorslogos:size=16}n${font}${voffset -6}${goto 32}${exec nvidia-smi --query-gpu=name --format=csv,noheader}${alignr}${nvidia gpufreqcur}MHz
```

and also usage monitoring, just below that:

```
${goto 6}${voffset 5}${font conkycolors:size=16}l${font}${voffset -6}${goto 32}Usage: ${nvidia gpuutil}%${alignr}${nvidiagraph gpuutil 8, 60}
```

I don't have a fixed public IP address, so I also added this snippet, below local ip:

```
${voffset 8}${font conkycolors:size=13}A${font}${goto 32}${voffset -4}Public IP: ${alignr}${execi 600 curl -s www.icanhazip.com}
```
Thanks!

**Comment by Martinsos** [comment]
@cmoro-deusto That is awesome, thanks!
I added the public IP to my conky also. I tried adding GPU improvements, however I don't have support for nvidia command in my conky. I figured I have to install conky-nvidia, however it fails during the installation. How did you get it working? Thanks!

**Comment by cmoro-deusto** [comment]
Regarding the nvidia stuff, you are totally right, I forgot to tell you about the prerequisites.
I actually installed this package from AUR https://aur.archlinux.org/packages/conky-lua-nv/
It's mainstream conky, compiled with nvidia and lua support and works perfectly. If not I can upload my package somewhere if you need it.
:) Funny thing, I face the same height constrainst in my laptop... I was thinking about dropping the processes list, or try to fiddle with the font sizes to make them even smaller... haven't decided yet!

**Comment by Martinsos** [comment]
Thanks for the info, I will check out that conky package!
Regarding the height -> at the end I split my conky into two conkies, one same as so far and the other one that only displays errors (since they were taking a lot of space).

**Comment by cmoro-deusto** [comment]
Of course!  Splitting it in two conkies is the way to go! Thanks a lot!
